version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Point to backend folder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy  # Ensures MongoDB is ready before backend starts
    env_file:
      - ./backend/.env  # Use .env from backend
    volumes:
      - ./backend:/app  # Mount backend folder
      - /app/node_modules  # Prevent overwriting node_modules

  frontend:
    build:
      context: ./frontend  # Point to frontend folder
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Correct port for Vite
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount frontend folder
      - /app/node_modules  # Prevent overwriting node_modules

  mongo:
    image: mongo
    container_name: my-mongo-db
    restart: always  # Restart MongoDB automatically if it fails
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
